#!/bin/bash
# apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances <your-package-here> | grep "^\w" | sort -u
# apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances <your-package-here> | grep "^\w" | sort -u)

apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances git openssh-server sssd-ad sssd-tools realmd adcli cmake make gcc g++ flex bison python-dev swig libpcap-dev libssl-dev zlib1g-dev libgeoip-dev curl PF_RING krb5 ipsumdump python3 python3-dev net-tools wireshark tshark tcpdump docker suricata gparted fdisk syslog-ng ntp | grep "^\w" | sort -u)

# timedatectl